services:
  db:
    image: mysql:8.4
    container_name: nobel-mysql-compose
    ports:
      - "9303:3306"
    volumes:
      - nobel-mysql-data:/var/lib/mysql

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: nobel-backend-compose
    env_file:
      - .env.docker
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: nobel-frontend-compose
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  nobel-mysql-data:
    external: true