"""baseline Nobel Explorer schema

Revision ID: 1439ccb7a517
Revises: 
Create Date: 2026-09-04 11:53:20.003380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1439ccb7a517'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('name', name='uq_category_name')
    )
    op.create_table('institution',
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('institution_id')
    )
    op.create_table('laureate',
    sa.Column('laureate_id', sa.Integer(), nullable=False),
    sa.Column('nobel_laureate_id', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('laureate_type', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('birth_city', sa.String(length=100), nullable=True),
    sa.Column('birth_state', sa.String(length=100), nullable=True),
    sa.Column('birth_country', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('image_source_url', sa.Text(), nullable=True),
    sa.Column('image_attribution', sa.Text(), nullable=True),
    sa.Column('image_license', sa.String(length=100), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('laureate_id'),
    sa.UniqueConstraint('nobel_laureate_id')
    )
    op.create_table('prize',
    sa.Column('prize_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.PrimaryKeyConstraint('prize_id')
    )
    op.create_table('laureate_prize',
    sa.Column('laureate_prize_id', sa.Integer(), nullable=False),
    sa.Column('laureate_id', sa.Integer(), nullable=False),
    sa.Column('prize_id', sa.Integer(), nullable=False),
    sa.Column('prize_share', sa.String(length=20), nullable=True),
    sa.Column('motivation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['laureate_id'], ['laureate.laureate_id'], ),
    sa.ForeignKeyConstraint(['prize_id'], ['prize.prize_id'], ),
    sa.PrimaryKeyConstraint('laureate_prize_id'),
    sa.UniqueConstraint('laureate_id', 'prize_id', name='uq_laureate_prize')
    )
    op.create_table('award_affiliation',
    sa.Column('award_affiliation_id', sa.Integer(), nullable=False),
    sa.Column('laureate_prize_id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.institution_id'], ),
    sa.ForeignKeyConstraint(['laureate_prize_id'], ['laureate_prize.laureate_prize_id'], ),
    sa.PrimaryKeyConstraint('award_affiliation_id'),
    sa.UniqueConstraint('laureate_prize_id', 'institution_id', name='uq_award_affiliation')
    )
    op.create_table('discovery',
    sa.Column('discovery_id', sa.Integer(), nullable=False),
    sa.Column('laureate_prize_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('significance', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['laureate_prize_id'], ['laureate_prize.laureate_prize_id'], ),
    sa.PrimaryKeyConstraint('discovery_id')
    )
    op.create_table('application',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('discovery_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['discovery_id'], ['discovery.discovery_id'], ),
    sa.PrimaryKeyConstraint('application_id')
    )
    op.create_table('quiz_question',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('discovery_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('choice_a', sa.String(length=500), nullable=False),
    sa.Column('choice_b', sa.String(length=500), nullable=False),
    sa.Column('choice_c', sa.String(length=500), nullable=False),
    sa.Column('choice_d', sa.String(length=500), nullable=False),
    sa.Column('correct_answer', sa.String(length=10), nullable=False),
    sa.Column('answer_explanation', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['discovery_id'], ['discovery.discovery_id'], ),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('explanation',
    sa.Column('explanation_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('explanation_text', sa.Text(), nullable=False),
    sa.Column('key_concepts', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['application.application_id'], ),
    sa.PrimaryKeyConstraint('explanation_id'),
    sa.UniqueConstraint('application_id', 'level', name='uq_explanation_application_level')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('explanation')
    op.drop_table('quiz_question')
    op.drop_table('application')
    op.drop_table('discovery')
    op.drop_table('award_affiliation')
    op.drop_table('laureate_prize')
    op.drop_table('prize')
    op.drop_table('laureate')
    op.drop_table('institution')
    op.drop_table('category')
    # ### end Alembic commands ###
