from backend.models.category import Category
from backend.models.prize import Prize
from backend.models.laureate import Laureate
from backend.models.laureate_prize import LaureatePrize
from backend.models.discovery import Discovery
from backend.models.application import Application
from backend.models.explanation import Explanation
from backend.models.quiz_question import QuizQuestion
from backend.models.institution import Institution
from backend.models.award_affiliation import AwardAffiliation