from backend.models.category import Category
from backend.models.prize import Prize
from backend.models.laureate import Laureate
from backend.models.laureate_prize import LaureatePrize
from backend.models.contribution import Contribution
from backend.models.contribution_laureate import ContributionLaureate
from backend.models.connection import Connection
from backend.models.explanation import Explanation
from backend.models.quiz_question import QuizQuestion
from backend.models.institution import Institution
from backend.models.award_affiliation import AwardAffiliation
