const COUNTRY_ISO_CODES = {
  USA: "US",
  "United Kingdom": "GB",
  Scotland: "GB",
  "Northern Ireland": "GB",
  Ireland: "IE",
  Germany: "DE",
  "West Germany": "DE",
  Bavaria: "DE",
  Mecklenburg: "DE",
  "Hesse-Kassel": "DE",
  Württemberg: "DE",
  "East Friesland": "DE",
  France: "FR",
  "Guadeloupe, France": "GP",
  Japan: "JP",
  Sweden: "SE",
  Canada: "CA",
  "the Netherlands": "NL",
  Switzerland: "CH",
  Russia: "RU",
  Italy: "IT",
  Tuscany: "IT",
  Austria: "AT",
  Norway: "NO",
  Denmark: "DK",
  "Faroe Islands (Denmark)": "FO",
  China: "CN",
  India: "IN",
  Australia: "AU",
  Hungary: "HU",
  Belgium: "BE",
  "Belgian Congo": "CD",
  "South Africa": "ZA",
  Poland: "PL",
  "German-occupied Poland": "PL",
  "Free City of Danzig": "PL",
  Spain: "ES",
  Egypt: "EG",
  Argentina: "AR",
  Romania: "RO",
  "New Zealand": "NZ",
  Mexico: "MX",
  Turkey: "TR",
  "French Algeria": "DZ",
  Venezuela: "VE",
  Finland: "FI",
  "East Timor": "TL",
  Korea: "KR",
  "South Korea": "KR",
  Portugal: "PT",
  Liberia: "LR",
  Colombia: "CO",
  Luxembourg: "LU",
  Chile: "CL",
  Guatemala: "GT",
  Iran: "IR",
  Persia: "IR",
  Lithuania: "LT",
  Ethiopia: "ET",
  "Southern Rhodesia": "ZW",
  Lebanon: "LB",
  Burma: "MM",
  Cyprus: "CY",
  Madagascar: "MG",
  "Saint Lucia": "LC",
  Bulgaria: "BG",
  Iceland: "IS",
  Bosnia: "BA",
  "Gold Coast": "GH",
  Vietnam: "VN",
  Pakistan: "PK",
  Philippines: "PH",
  Peru: "PE",
  Iraq: "IQ",
  Crete: "GR",
  Jordan: "JO",
  "Costa Rica": "CR",
  Brazil: "BR",
  "French protectorate of Tunisia": "TN",
  Morocco: "MA",
  Ukraine: "UA",
  Yemen: "YE",
  "Trinidad and Tobago": "TT",
  Kenya: "KE",
  "Java, Dutch East Indies": "ID",
  Nigeria: "NG",
  Taiwan: "TW",
};

export function getCountryFlag(countryName) {
  const code = COUNTRY_ISO_CODES[countryName];
  if (!code) return null;

  return code
    .toUpperCase()
    .replace(/./g, (letter) => String.fromCodePoint(127397 + letter.charCodeAt(0)));
}
